version: '3.8'
services:
  juiceshop:
    image: bkimminich/juice-shop
    ports:
      - "3001:3000" # Juice Shop UI 端口保持不变

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: juiceshop_db
    ports:
      - "5433:5432" # 变更: 主机端口改为5433，容器内部依然是5432

  mongo-db:
    image: mongo:4
    ports:
      - "27018:27017" # 变更: 主机端口改为27018，容器内部依然是27017

  # 我们的攻击和测试客户端
  attack-client:
    image: ubuntu:20.04
    tty: true # 保持容器运行以便我们进入
    command: /bin/bash
    depends_on:
      - juiceshop
      - postgres-db
      - mongo-db

networks:
  default:
    driver: bridge
